name: DevSecOps Pipeline

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Run OWASP Dependency-Check
      run: mvn org.owasp:dependency-check-maven:check

    - name: Archive OWASP Dependency-Check Report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: target/dependency-check-report.html

    - name: Run SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v1
      with:
        args: >
          -Dsonar.projectKey=devsecops-java-project
          -Dsonar.projectName=DevSecOps Java Project
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Build Docker image
      run: docker build -t devsecops-java-app .

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy

    - name: Scan Docker image with Trivy
      run: trivy image devsecops-java-app

    - name: Archive Trivy Report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: trivy-image-report.txt
